version: "3.7"

services:
  # Redis
  redis:
    container_name: desafio-blumpa-redis
    image: redis
    ports:
      - "6379:6379"
  # API
  blumpa-api:
    container_name: desafio-blumpa-api
    build: .
    entrypoint: ./docker-entrypoint.sh
    command: ["foreman", "start"]
    working_dir: /usr/src/desafio-blumpa
    links:
      - redis
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/desafio-blumpa
